alpha1_witness_names = [f'witness{i}' for i in range(4)]
alpha2_witness_names = [f'witness{i}' for i in range(4, 8)]
beta1_witness_names = [f'witness{i}' for i in range(8, 12)]
beta2_witness_names = [f'witness{i}' for i in range(12, 16)]
gamma1_witness_names = [f'witness{i}' for i in range(16, 20)]
gamma2_witness_names = [f'witness{i}' for i in range(20, 25)]
