from ..node_config import NodeConfig

DEFAULT_CONFIG = NodeConfig()

DEFAULT_CONFIG.log_appender = '{"appender":"stderr","stream":"std_error"} {"appender":"p2p","file":"logs/p2p/p2p.log"}'
DEFAULT_CONFIG.log_logger = '{"name":"default","level":"info","appender":"stderr"} {"name":"p2p","level":"warn","appender":"p2p"}'
DEFAULT_CONFIG.backtrace = 'yes'
DEFAULT_CONFIG.plugin = ['witness', 'account_by_key', 'account_by_key_api', 'condenser_api']
DEFAULT_CONFIG.history_disable_pruning = '0'
DEFAULT_CONFIG.account_history_rocksdb_path = 'blockchain/account-history-rocksdb-storage'
DEFAULT_CONFIG.block_data_export_file = 'NONE'
DEFAULT_CONFIG.block_log_info_print_interval_seconds = '86400'
DEFAULT_CONFIG.block_log_info_print_irreversible = '1'
DEFAULT_CONFIG.block_log_info_print_file = 'ILOG'
DEFAULT_CONFIG.shared_file_dir = 'blockchain'
DEFAULT_CONFIG.shared_file_size = '54G'
DEFAULT_CONFIG.shared_file_full_threshold = '0'
DEFAULT_CONFIG.shared_file_scale_rate = '0'
DEFAULT_CONFIG.follow_max_feed_size = '500'
DEFAULT_CONFIG.follow_start_feeds = '0'
DEFAULT_CONFIG.market_history_bucket_size = '[15,60,300,3600,86400]'
DEFAULT_CONFIG.market_history_buckets_per_size = '5760'
DEFAULT_CONFIG.rc_skip_reject_not_enough_rc = '0'
DEFAULT_CONFIG.rc_compute_historical_rc = '0'
DEFAULT_CONFIG.rc_start_at_block = '0'
DEFAULT_CONFIG.snapshot_root_dir = 'snapshot'
DEFAULT_CONFIG.statsd_batchsize = '1'
DEFAULT_CONFIG.tags_start_promoted = '0'
DEFAULT_CONFIG.tags_skip_startup_update = '0'
DEFAULT_CONFIG.transaction_status_block_depth = '64000'
DEFAULT_CONFIG.transaction_status_track_after_block = '0'
DEFAULT_CONFIG.webserver_thread_pool_size = '32'
DEFAULT_CONFIG.enable_stale_production = '0'
DEFAULT_CONFIG.required_participation = '33'
DEFAULT_CONFIG.witness_skip_enforce_bandwidth = '1'
