macro(protocol_assert_id sources binary_dir)

  message("Beginning verification of assertion's given id in protocol namespace")

  set(protocol_assert_expressions)

  foreach(file ${sources})
    #message("file: ${file}")
    file(REAL_PATH ${file} real_path)
    message(${real_path})
    file(READ ${real_path} file_contents)
    list(FILTER file_contents INCLUDE REGEX "FC_ASSERT[ \r\n]*\\(" )
    if(NOT "${file_contents}" STREQUAL "")
      foreach(line ${file_contents})
        string(FIND ${line} "FC_ASSERT" start)
        string(FIND ${line} ")" stop REVERSE)
        math(EXPR length "${stop} - ${start} +1")
        string(SUBSTRING ${line} ${start} ${length} assertion)
        #message(">>${assertion}<<")

        # Extract substring of assertion expression
        string(FIND ${assertion} "(" current_pos)
        string(FIND ${assertion} ")" stop REVERSE)
        math(EXPR current_pos "${current_pos} +1")
        math(EXPR length "${stop} - ${current_pos}")
        string(SUBSTRING ${assertion} ${current_pos} ${length} assert_expr)
        #message(">>${assert_expr}<<")

        # Trim assertion message (& its params) if present
        string(FIND ${assert_expr} "," comma_pos)
        string(FIND ${assert_expr} "(" current_pos)
        string(LENGTH ${assert_expr} assert_expr_length)
        while(${comma_pos} GREATER -1 AND ${current_pos} GREATER -1 AND ${comma_pos} GREATER ${current_pos})
          # Scroll to closing parenthesis
          #message("Looking for parenthesis closing the one at ${current_pos}")
          math(EXPR open_count "1")
          while(${open_count} GREATER 0 AND ${current_pos} LESS ${assert_expr_length})
            math(EXPR current_pos "${current_pos} +1")
            string(SUBSTRING ${assert_expr} ${current_pos} 1 another_byte)
            if("${another_byte}" STREQUAL ")")
              math(EXPR open_count "${open_count} -1")
            elseif("${another_byte}" STREQUAL ")")
              math(EXPR open_count "${open_count} +1")
            endif()
          endwhile()
          if(${current_pos} EQUAL ${assert_expr_length})
            break()
          endif()
          string(SUBSTRING ${assert_expr} ${current_pos} -1 expr_remainder)
          if(${comma_pos} LESS ${current_pos})
            # Ignore comma inside parentheses. Look for another comma.
            string(FIND ${expr_remainder} "," comma_pos)
            if(${comma_pos} GREATER -1)
              math(EXPR comma_pos "${comma_pos} +${current_pos}")
            endif()
          else()
            # There may be another parentheses containing the comma.
            string(FIND ${expr_remainder} "(" new_paren_pos)
            if(${new_paren_pos} GREATER -1)
              math(EXPR current_pos "${current_pos} +${new_paren_pos}")
            endif()          
          endif()
        endwhile()
        if(${comma_pos} GREATER -1)
          string(SUBSTRING ${assert_expr} 0 ${comma_pos} assert_expr)
          #message("TRIMMED!>>${assert_expr}<<")
        endif()
        
        string(STRIP ${assert_expr} trimmed_expr)
        list(APPEND protocol_assert_expressions "//${trimmed_expr}\n")
      endforeach()
    #message(">> ${file_contents} <<")
    endif()
  endforeach()

set(OUT_FILE "${binary_dir}/protocol_assert_expressions.hpp" )
file(WRITE ${OUT_FILE} ${protocol_assert_expressions} )


endmacro()