repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: [ "--autofix" ]
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/python-poetry/poetry
    rev: 1.6.1
    hooks:
      - id: poetry-lock
        name: checking if poetry.lock is consistent with pyproject.toml
        args: [ "--no-update" ]
        language_version: python3.10
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.277'
    hooks:
      - id: ruff
        name: linting code with Ruff
        args: [ "--fix" ]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: format code using black
  - repo: local
    hooks:
    - id: mypy
      name: type check with mypy
      entry: mypy
      language: system
      types: [ python ]
