from __future__ import annotations

def validate_operation(operation: bytes) -> bool | None: ...
def validate_transaction(transaction: bytes) -> bool | None: ...
def calculate_digest(transaction: bytes, chain_id: bytes) -> tuple[bool, str] | None: ...
def serialize_transaction(transaction: bytes) -> bool | None: ...
