[build-system]
requires = [
    "poetry-core>=1.7.0",
    "poetry-dynamic-versioning>=1.0.0,<2.0.0",
]
build-backend = "poetry_dynamic_versioning.backend"


[tool.poetry]
name = "hived_inputs"
version = "0.0.0"
description = ""
authors = []
package-mode=true

packages = [
    { include = "hived_inputs" },
]
include = [
    { path =  "hived_inputs/*", format = ["wheel", "sdist"] }
]
source = [
    { name = "PyPI", priority = "primary" },
    { name = "gitlab-schemas", url = "https://gitlab.syncad.com/api/v4/projects/362/packages/pypi/simple", priority = "supplemental" },
    { name = "gitlab-beekeepy", url = "https://gitlab.syncad.com/api/v4/projects/434/packages/pypi/simple", priority = "supplemental" },
]

[tool.poetry.dependencies]
python = "^3.12"
beekeepy = "0.0.1.dev413+0bc0d4b" # Please remember that this version is copied to the generated API packages.

[tool.poetry-dynamic-versioning]
enable = true
pattern = '''^v?(?P<base>\d+\.\d+\.\d+)(?:(?P<stage>[a-zA-Z]+)(?P<revision>\d+))?$'''
format-jinja = """
    {%- if distance == 0 and not dirty -%}
        {{ serialize_pep440(base, stage, revision) }}
    {%- elif revision is not none -%}
        {{ serialize_pep440(base, stage, revision + 1, dev=distance, metadata=[commit]) }}
    {%- else -%}
        {{ serialize_pep440(bump_version(base), stage, revision, dev=distance, metadata=[commit]) }}
    {%- endif -%}
"""


[tool.poetry-dynamic-versioning.substitution]
files = [
    "hived_inputs/__init__.py",
]
